network:
  version: 2
  renderer: networkd

  ethernets:
    enp1s0:
      addresses: [192.168.1.35/24]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.1.1
      nameservers:
        addresses: [8.8.8.8]
