network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      addresses:
        - 192.168.1.25/24
      routes:
        - to: default
          via: 192.168.1.1
          metric: 200
      nameservers:
        addresses:
          - 8.8.8.8      
